apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: ufc-platform
  labels:
    app: ufc-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ufc-api
  template:
    metadata:
      labels:
        app: ufc-api
        version: v1
    spec:
      containers:
      - name: api
        image: ufc-platform/api:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ufc-platform-config
              key: API_PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ufc-platform-config
              key: NODE_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ufc-platform-config
              key: LOG_LEVEL
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: ufc-platform-secrets
              key: MONGODB_URI
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ufc-platform-secrets
              key: REDIS_URL
        - name: INFLUXDB_URL
          valueFrom:
            secretKeyRef:
              name: ufc-platform-secrets
              key: INFLUXDB_URL
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: ufc-platform-secrets
              key: INFLUXDB_TOKEN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ufc-platform-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ufc-platform
  labels:
    app: ufc-api
spec:
  selector:
    app: ufc-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: ufc-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80